CREATE TABLE USER_INFO(USER_ID INT PRIMARY KEY,
    NAME VARCHAR(30), EMAIL VARCHAR(300),MOBILE VARCHAR(300),
    USERNAME VARCHAR(30) , PASSWORD VARCHAR(30));
    
CREATE UNIQUE INDEX UK_USERNAME_INDX ON USER_INFO(USERNAME);